name: Build Shadowrocket Rules

on:
  push:
    paths:
      - "rules/**"
      - "scripts/**"
  pull_request:
    paths:
      - "rules/**"
      - "scripts/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Lint rules
        run: python scripts/build.py

      - name: Commit build files
        if: github.event_name == 'push'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add build/

          git diff --cached --quiet && echo "No changes to commit" && exit 0

          git commit -m "auto update rules"
          git push
